### ISSUE TITLE
Is this ready for production ?

### ISSUE THREAD

**Issue by EssaAlshammri** [anx-ckreuzberger/django-rest-multiauthtoken#1]
Hi @anx-ckreuzberger 

You did an awesome job, your project will make my life easier. Thank you so much.
I can make use of it on a project I'm working on, and I have tested it and it works as expected. 

but the thing is, is it ready to be used in production.
if not can you point me to something similar.

 Thank you.

**Comment by anx-ckreuzberger** [comment]
Short answer: Yes. 
Please take a look into the [Releases](https://github.com/anx-ckreuzberger/django-rest-multiauthtoken/releases) page.
